### ISSUE TITLE
  java.lang.IllegalStateException

### ISSUE THREAD

**Issue by as11051105** [yinhaide/HDRocket#2]
java.lang.IllegalStateException
        at android.media.MediaPlayer.isPlaying(Native Method)
        at com.lungfish.ielts.support.mediadeal.MediaPlayerHelper$1.run(MediaPlayerHelper.java:229)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by yinhaide** [comment]
try {
   if (mediaPlayer.isPlaying()) {              
    }
} catch (IllegalStateException e) {

}
